version: '3'
services:
  sre_assignment:
    image: iamankush94/sre_assignment:latest
    container_name: iamankush08
    ports:
      - "9393:7177"
    env_file:
      - sreassignment.env
    volumes:
      - /root/generated.csv:/home/node/app/csv/generated.csv
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    working_dir: /prometheus
    depends_on:
      - sre_assignment
volumes:
  prometheus-data:
